### ISSUE TITLE
specBrowser task doesn't work in travis

### ISSUE THREAD

**Issue by tandrewnichols** [linemanjs/lineman-spec-browser#11]
Something fails in the browser helper, which causes all the tests that rely on `browser` to fail with `Reference Error: browser is not defined`.

Here's the failure output:

```
1) Exception loading: /home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/helpers/browser.coffee Error
   Message:
     Error: libjvm.so: cannot open shared object file: No such file or directory
   Stacktrace:
     Error: libjvm.so: cannot open shared object file: No such file or directory
    at Module.load (/home/travis/build/mantacode/manta-frontend/client/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/node_modules/webdriver-sync/node_modules/java/lib/nodeJavaBridge.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/home/travis/build/mantacode/manta-frontend/client/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/node_modules/webdriver-sync/node_modules/java/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/home/travis/build/mantacode/manta-frontend/client/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/node_modules/webdriver-sync/src/webdriver-sync.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/home/travis/build/mantacode/manta-frontend/client/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/helpers/browser.coffee:4:19)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman-spec-browser/helpers/browser.coffee:30:4)
    at Module._compile (module.js:456:26)
    at Object.require.extensions..coffee (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (/home/travis/build/mantacode/manta-frontend/client/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.executeSpecs (/home/travis/build/mantacode/manta-frontend/client/node_modules/grunt-jasmine-bundle/node_modules/minijasminenode/lib/index.js:116:7)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/grunt-jasmine-bundle/lib/task-generator.coffee:28:26)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/grunt/task.js:258:15)
    at Object.thisTask.fn (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:215:7)
    at Task.runTaskFn (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:238:9)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:215:7)
    at Task.runTaskFn (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:238:9)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:215:7)
    at null._onTimeout (/home/travis/build/mantacode/manta-frontend/client/node_modules/lineman/node_modules/grunt/lib/util/task.js:225:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by tandrewnichols** [comment]
This might be because we, at some point, took webdriver-sync out of package.json. Not sure when or why. I'll confirm if that's the issue.

**Comment by tandrewnichols** [comment]
Ah, we took it out because this uses it's own version. And I think that has to happen. When I add webdriver-sync to our node_modules, the phantomjs specBrowser task hangs after like the first 5 tests (not sure why THERE, but it's pretty consistent).
